name: ci

on:
  pull_request:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancels in progress workflows on PRs.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Restore cargo cache
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Rustup Show
      run: rustup show

    - name: Cargo fmt --check
      run: cargo fmt --all -- --check

    - name: Cargo Check
      run: cargo c

    - name: Cargo Test
      run: cargo t

    - name: Cargo Clippy
      run: cargo clippy